(ns se.jherrlin.iban.lib.specs
  (:require
   [clojure.spec.alpha]))


(clojure.spec.alpha/def
  :se.jherrlin.iban/TL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^TL\\d{2}\\d{3}\\d{14}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SA
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SA\\d{2}\\d{2}[a-zA-Z0-9]{18}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LU
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LU\\d{2}\\d{3}[a-zA-Z0-9]{13}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/PT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^PT\\d{2}\\d{4}\\d{4}\\d{11}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/KW
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^KW\\d{2}[A-Z]{4}[a-zA-Z0-9]{22}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/IL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^IL\\d{2}\\d{3}\\d{3}\\d{13}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/QA
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^QA\\d{2}[A-Z]{4}[a-zA-Z0-9]{21}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SC
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SC\\d{2}[A-Z]{4}\\d{2}\\d{2}\\d{16}[A-Z]{3}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^BE\\d{2}\\d{3}\\d{7}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/VA
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^VA\\d{2}\\d{3}\\d{15}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GT\\d{2}[a-zA-Z0-9]{4}[a-zA-Z0-9]{20}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MC
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^MC\\d{2}\\d{5}\\d{5}[a-zA-Z0-9]{11}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SK
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SK\\d{2}\\d{4}\\d{6}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/IT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^IT\\d{2}[A-Z]{1}\\d{5}\\d{5}[a-zA-Z0-9]{12}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/CY
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^CY\\d{2}\\d{3}\\d{5}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GB
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GB\\d{2}[A-Z]{4}\\d{6}\\d{8}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/PS
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^PS\\d{2}[A-Z]{4}[a-zA-Z0-9]{21}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/HR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^HR\\d{2}\\d{7}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/DK
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^DK\\d{2}\\d{4}\\d{9}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/IQ
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^IQ\\d{2}[A-Z]{4}\\d{3}\\d{12}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SE\\d{2}\\d{3}\\d{16}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/DO
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^DO\\d{2}[a-zA-Z0-9]{4}\\d{20}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LC
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LC\\d{2}[A-Z]{4}[a-zA-Z0-9]{24}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GL\\d{2}\\d{4}\\d{9}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/ST
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^ST\\d{2}\\d{4}\\d{4}\\d{11}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/AE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^AE\\d{2}\\d{3}\\d{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/JO
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^JO\\d{2}[A-Z]{4}\\d{4}[a-zA-Z0-9]{18}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SM
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SM\\d{2}[A-Z]{1}\\d{5}\\d{5}[a-zA-Z0-9]{12}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/FO
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^FO\\d{2}\\d{4}\\d{9}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SV
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SV\\d{2}[A-Z]{4}\\d{20}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GI
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GI\\d{2}[A-Z]{4}[a-zA-Z0-9]{15}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MU
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern
       "^MU\\d{2}[A-Z]{4}\\d{2}\\d{2}\\d{12}\\d{3}[A-Z]{3}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/AL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^AL\\d{2}\\d{8}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LY
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LY\\d{2}\\d{3}\\d{3}\\d{15}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/IS
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^IS\\d{2}\\d{4}\\d{2}\\d{6}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LB
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LB\\d{2}\\d{4}[a-zA-Z0-9]{20}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/ME
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^ME\\d{2}\\d{3}\\d{13}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LV
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LV\\d{2}[A-Z]{4}[a-zA-Z0-9]{13}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/SI
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^SI\\d{2}\\d{5}\\d{8}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MD
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^MD\\d{2}[a-zA-Z0-9]{2}[a-zA-Z0-9]{18}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/RO
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^RO\\d{2}[A-Z]{4}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/AD
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^AD\\d{2}\\d{4}\\d{4}[a-zA-Z0-9]{12}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BA
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^BA\\d{2}\\d{3}\\d{3}\\d{8}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/VG
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^VG\\d{2}[A-Z]{4}\\d{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/RS
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^RS\\d{2}\\d{3}\\d{13}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/XK
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^XK\\d{2}\\d{4}\\d{10}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MK
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^MK\\d{2}\\d{3}[a-zA-Z0-9]{10}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/NL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^NL\\d{2}[A-Z]{4}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern
       "^BR\\d{2}\\d{8}\\d{5}\\d{10}[A-Z]{1}[a-zA-Z0-9]{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/EE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^EE\\d{2}\\d{2}\\d{2}\\d{11}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/CR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^CR\\d{2}\\d{4}\\d{14}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/TR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^TR\\d{2}\\d{5}\\d{1}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LT\\d{2}\\d{5}\\d{11}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/IE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^IE\\d{2}[A-Z]{4}\\d{6}\\d{8}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/ES
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^ES\\d{2}\\d{4}\\d{4}\\d{1}\\d{1}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/AT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^AT\\d{2}\\d{5}\\d{11}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BH
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^BH\\d{2}[A-Z]{4}[a-zA-Z0-9]{14}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GE\\d{2}[A-Z]{2}\\d{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/TN
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^TN\\d{2}\\d{2}\\d{3}\\d{13}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BG
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^BG\\d{2}[A-Z]{4}\\d{4}\\d{2}[a-zA-Z0-9]{8}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/NO
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^NO\\d{2}\\d{4}\\d{6}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/PK
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^PK\\d{2}[A-Z]{4}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/GR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^GR\\d{2}\\d{3}\\d{4}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/AZ
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^AZ\\d{2}[A-Z]{4}[a-zA-Z0-9]{20}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^MR\\d{2}\\d{5}\\d{5}\\d{11}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/FR
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^FR\\d{2}\\d{5}\\d{5}[a-zA-Z0-9]{11}\\d{2}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/PL
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^PL\\d{2}\\d{8}\\d{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/FI
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^FI\\d{2}\\d{3}\\d{11}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/MT
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^MT\\d{2}[A-Z]{4}\\d{5}[a-zA-Z0-9]{18}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/BY
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^BY\\d{2}[a-zA-Z0-9]{4}\\d{4}[a-zA-Z0-9]{16}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/CH
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^CH\\d{2}\\d{5}[a-zA-Z0-9]{12}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/EG
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^EG\\d{2}\\d{4}\\d{4}\\d{17}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/CZ
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^CZ\\d{2}\\d{4}\\d{6}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/KZ
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^KZ\\d{2}\\d{3}[a-zA-Z0-9]{13}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/HU
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^HU\\d{2}\\d{3}\\d{4}\\d{1}\\d{15}\\d{1}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/UA
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^UA\\d{2}\\d{6}[a-zA-Z0-9]{19}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/DE
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^DE\\d{2}\\d{8}\\d{10}$")
      s))))
(clojure.spec.alpha/def
  :se.jherrlin.iban/LI
  (clojure.spec.alpha/and
   clojure.core/string?
   (clojure.core/fn
     [s]
     (clojure.core/re-find
      (clojure.core/re-pattern "^LI\\d{2}\\d{5}[a-zA-Z0-9]{12}$")
      s))))
(clojure.spec.alpha/def
 :se.jherrlin.iban/iban
 (clojure.spec.alpha/or
  :TL
  :se.jherrlin.iban/TL
  :SA
  :se.jherrlin.iban/SA
  :LU
  :se.jherrlin.iban/LU
  :PT
  :se.jherrlin.iban/PT
  :KW
  :se.jherrlin.iban/KW
  :IL
  :se.jherrlin.iban/IL
  :QA
  :se.jherrlin.iban/QA
  :SC
  :se.jherrlin.iban/SC
  :BE
  :se.jherrlin.iban/BE
  :VA
  :se.jherrlin.iban/VA
  :GT
  :se.jherrlin.iban/GT
  :MC
  :se.jherrlin.iban/MC
  :SK
  :se.jherrlin.iban/SK
  :IT
  :se.jherrlin.iban/IT
  :CY
  :se.jherrlin.iban/CY
  :GB
  :se.jherrlin.iban/GB
  :PS
  :se.jherrlin.iban/PS
  :HR
  :se.jherrlin.iban/HR
  :DK
  :se.jherrlin.iban/DK
  :IQ
  :se.jherrlin.iban/IQ
  :SE
  :se.jherrlin.iban/SE
  :DO
  :se.jherrlin.iban/DO
  :LC
  :se.jherrlin.iban/LC
  :GL
  :se.jherrlin.iban/GL
  :ST
  :se.jherrlin.iban/ST
  :AE
  :se.jherrlin.iban/AE
  :JO
  :se.jherrlin.iban/JO
  :SM
  :se.jherrlin.iban/SM
  :FO
  :se.jherrlin.iban/FO
  :SV
  :se.jherrlin.iban/SV
  :GI
  :se.jherrlin.iban/GI
  :MU
  :se.jherrlin.iban/MU
  :AL
  :se.jherrlin.iban/AL
  :LY
  :se.jherrlin.iban/LY
  :IS
  :se.jherrlin.iban/IS
  :LB
  :se.jherrlin.iban/LB
  :ME
  :se.jherrlin.iban/ME
  :LV
  :se.jherrlin.iban/LV
  :SI
  :se.jherrlin.iban/SI
  :MD
  :se.jherrlin.iban/MD
  :RO
  :se.jherrlin.iban/RO
  :AD
  :se.jherrlin.iban/AD
  :BA
  :se.jherrlin.iban/BA
  :VG
  :se.jherrlin.iban/VG
  :RS
  :se.jherrlin.iban/RS
  :XK
  :se.jherrlin.iban/XK
  :MK
  :se.jherrlin.iban/MK
  :NL
  :se.jherrlin.iban/NL
  :BR
  :se.jherrlin.iban/BR
  :EE
  :se.jherrlin.iban/EE
  :CR
  :se.jherrlin.iban/CR
  :TR
  :se.jherrlin.iban/TR
  :LT
  :se.jherrlin.iban/LT
  :IE
  :se.jherrlin.iban/IE
  :ES
  :se.jherrlin.iban/ES
  :AT
  :se.jherrlin.iban/AT
  :BH
  :se.jherrlin.iban/BH
  :GE
  :se.jherrlin.iban/GE
  :TN
  :se.jherrlin.iban/TN
  :BG
  :se.jherrlin.iban/BG
  :NO
  :se.jherrlin.iban/NO
  :PK
  :se.jherrlin.iban/PK
  :GR
  :se.jherrlin.iban/GR
  :AZ
  :se.jherrlin.iban/AZ
  :MR
  :se.jherrlin.iban/MR
  :FR
  :se.jherrlin.iban/FR
  :PL
  :se.jherrlin.iban/PL
  :FI
  :se.jherrlin.iban/FI
  :MT
  :se.jherrlin.iban/MT
  :BY
  :se.jherrlin.iban/BY
  :CH
  :se.jherrlin.iban/CH
  :EG
  :se.jherrlin.iban/EG
  :CZ
  :se.jherrlin.iban/CZ
  :KZ
  :se.jherrlin.iban/KZ
  :HU
  :se.jherrlin.iban/HU
  :UA
  :se.jherrlin.iban/UA
  :DE
  :se.jherrlin.iban/DE
  :LI
  :se.jherrlin.iban/LI))
